
[Interface]
Address = 10.101.0.16/32
PrivateKey = mPvysrX4tHNyz4BsbDDXHFOiyAn5c/qG3s23MxxUV1M=
PostUp = printf 'You can now access http://0.0.0.0:8080 on https://yph1by.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = AafCbIVmjxkEPZNWEe6hlm0y8WS49RMaow8JIA5xu3U=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
